import Config

# Configure your database
#
# The `pot_examples`-style Postgres container used by
# `learn_erl/power-of-three-examples` maps 5432 → 17432 on the host. If
# you run your own Postgres on 5432, set `PG_PORT=5432` to override.
config :prizeflight, Prizeflight.Repo,
  port: String.to_integer(System.get_env("PG_PORT") || "17432"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :prizeflight, PrizeflightWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "X1SFhTBX46oVwyWtbuwtM8qCfHB2BLPcZETQUS0Eum3RqfWhXlBYOFkprMiyJIUp",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Seed 1M synthetic price events on first startup so the Cube.js
# Playground has data to chart. Skipped when `price_events` already
# has rows. Override via `SEED_COUNT` or disable with
# `config :prizeflight, :seed_on_empty, false`.
config :prizeflight,
  seed_on_empty: true,
  seed_count: String.to_integer(System.get_env("SEED_COUNT") || "1000000"),
  seed_concurrency:
    String.to_integer(System.get_env("SEED_CONCURRENCY") || "16")

# Enable dev routes for dashboard and mailbox
config :prizeflight, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
